# Generated by Django 3.1 on 2020-08-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200827_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
